### ISSUE TITLE
We should explicitly talk about "mySociety Services"

### ISSUE THREAD

**Issue by mikejamesthompson** [mysociety/annual-report#19]
I can't give you an exact wording because it probably has structural implications as well, but something like:

> mySociety is a consultancy and web agency, too
> we're known as mySociety Services
> In 2014, we worked with more than 30 clients including the British Museum, the Money Advice Service, > the Financial Conduct Authority, and the UK Parliament.

Then somewhere on that page introduce the new website. I leave that up to you to decide how to do that.

**Comment by zarino** [comment]
Does this also extend to the section being named "Services" rather than "Commercial"? Or is that fine to stay?
