### ISSUE TITLE
Needs to go on a proper domain

### ISSUE THREAD

**Issue by zarino** [mysociety/annual-report#23]
Do we have a subdomain like something.mysociety.org? Or a subdirectory, like mysociety.org/something? And do we put the year in it?

@paullenz @wrightmartin @dracos – Any preference?

**Comment by dracos** [comment]
2014.mysociety.org would get my vote.

**Comment by wrightmartin** [comment]
> 2014.mysociety.org would get my vote.

Yep, I agree

**Comment by zarino** [comment]
Ace.

@dracos – can you organise this? (If it makes it any easier, it's worth pointing out this is just a Jekyll site, so we could use Github pages if you wanted?)

**Comment by dracos** [comment]
"we could use Github pages if you wanted" - I'd like it to be SSL, so it'll have to be us.

**Comment by dracos** [comment]
Done.
