### ISSUE TITLE
annotate the future image (colleagues on a Santiago roof)

### ISSUE THREAD

**Issue by davewhiteland** [mysociety/annual-report#24]
That photo could easily be mistaken for a stock photo -- maybe worth a (small font?) annotation pointing out it's some of the team at the end of a day in Santiago for the PoplusCon event? Cos that is pretty cool, you guys!

**Comment by davewhiteland** [comment]
I think that absolute positioning is trampling your lovely responsive design on narrow devices :-(

**Comment by zarino** [comment]
Fixed!
