### ISSUE TITLE
need a spot on the map for KL, Malaysia

### ISSUE THREAD

**Issue by davewhiteland** [mysociety/annual-report#25]
Just noticed we're missing a spot for the Sinar guys, I was there in 2014!

**Comment by davewhiteland** [comment]
hold that thought as I am trying to prove to myself that I did indeed go in 2014 :-/

**Comment by davewhiteland** [comment]
Confirmed -- March 2014. Spot it! (I think we'd already counted it in the country count though)

**Comment by paullenz** [comment]
I didn't think the spots on the map represented actual places we had been -
they were just spots...

**Comment by davewhiteland** [comment]
Well that's silly!  It's a map on an annual report about where we've been in the year :-O

**Comment by paullenz** [comment]
I will leave Zarino to comment - I could be wrong, but that was what I
surmised from looking at it

**Comment by zarino** [comment]
They are *roughly* the places listed in the original content document:

* Germany
* Rwanda
* Liberia
* South Africa
* Kenya
* USA
* Italy
* Spain
* Myanmar
* Thailand
* China
* Taiwan
* Georgia
* Chile
* Argentina
* Uruguay
* Mexico
* Paraguay
* Croatia
* Romania
* Bulgaria
* Tanzania
* France
* Poland
* Panama

But it's entirely likely that I've missed items off that list, or misplaced the spots by a few degrees.

**Comment by davewhiteland** [comment]
Ah then sorry but it's 26 cos Malaysia was overlooked:

 1. Argentina
 1. Bulgaria
 1. Chile
 1. China
 1. Croatia
 1. France
 1. Georgia
 1. Germany
 1. Italy
 1. Kenya
 1. Liberia
 1. **Malaysia**
 1. Mexico
 1. Myanmar
 1. Panama
 1. Paraguay
 1. Poland
 1. Romania
 1. Rwanda
 1. South Africa
 1. Spain
 1. Taiwan
 1. Tanzania
 1. Thailand
 1. Uruguay
 1. USA

**Comment by paullenz** [comment]
So I think we might need to lose the dot that is around Jordan as no-one
went there (or close to is) - seeing that when glancing made me think that
they were *just dots*

Also Paraguay is a ways further down, but not vital

Tc

P.

**Comment by davewhiteland** [comment]
Heads up that if the number of countries is now 26, then that means the text copy "That’s five more countries than pop band One Direction visited on their 2014 tour" may need to change to **six**.
https://github.com/mysociety/annual-report/blob/master/international.html#L17

...because as far as I can tell (can't believe you've got me looking into this) the lads never played in Malaysia on the 2014 tour:

http://en.wikipedia.org/wiki/Where_We_Are_Tour_%28One_Direction%29
https://www.facebook.com/WeWantOneDirectionInMalaysia
