### ISSUE TITLE
Include funders' logos on last page

### ISSUE THREAD

**Issue by Gemmamysoc** [mysociety/annual-report#37]
We don't name our funders at the moment, but we probably should. They are:

- Omidyar Network
- The Indigo Trust
- Open Society Foundations
- The William and Flora Hewlett Foundation
- Making All Voices Count
- Microsoft
- The Joseph Rowntree Reform Trust
- Google.org
- Bytemark

**Comment by zarino** [comment]
Closed by https://github.com/mysociety/annual-report/commit/bce53f68548826c3fbcf1449203da85d0d6712f6
