### ISSUE TITLE
2016 theme

### ISSUE THREAD

**Issue by zarino** [mysociety/annual-report#38]
Feels like we should go a bit lighter and brighter than previous years, to better tie in with the new light and bright mysociety.org homepage.

The report this year is also split into the 3 practice areas, just like our website, so maybe there’s opportunity to borrow some of the assets (like the round porthole illustrations) for the report?

**Comment by zarino** [comment]
Some opening concepts:

![desktop](https://cloud.githubusercontent.com/assets/739624/20798995/b83489c0-b7d8-11e6-898a-052279ff35dc.png)

![desktop copy](https://cloud.githubusercontent.com/assets/739624/20799036/df8d8800-b7d8-11e6-864c-e0577fe43bf5.png)

I like the idea of highlighting the staff quotes in cute little speech bubbles. The hand-drawn look isn't something we normally use, so it stands out – in a good way, I hope. Here’s how they might look (although we’d never present so many in such close proximity):

![screen shot 2016-12-01 at 15 11 02](https://cloud.githubusercontent.com/assets/739624/20799033/da89f96a-b7d8-11e6-95bd-c191dcd065aa.png)

**Comment by wrightmartin** [comment]
Lovely work!

Minor notes
- The illustrations could be larger on the page headings
- The quotes from staff are lovely, but a photo accompanying them might do something to add some human touch?
- it looks like one or two of the illustrations have exported badly, I'll see if I can reexport them and add them below
