### ISSUE TITLE
number of commercial clients

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/annual-report#4]
It says 20 projects in the basics section, but 30 clients in the commercial section. @BenJam to check!

**Comment by BenJam** [comment]
currently have 54 clients and I think technically we worked on 25 projects last year.

**Comment by zarino** [comment]
Ah, so @BenJam @MyfanwyNixon – the count of clients isn't from *this year only*, which is how the number of clients can be higher than the number of projects in 2014.

@BenJam – if we only included clients we worked with in 2014, how many would there be?

**Comment by BenJam** [comment]
29!
