### ISSUE TITLE
2018 design

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/annual-report#49]
There's still plenty to add, but here are the **bare bones** of this year's copy for the Annual Report: https://docs.google.com/document/d/1rJYskNsuSM33eyjs_qtSe7BDCfHfDW3ypqxzBW-4_NQ/edit# 
NB it will change/improve. I'll make all additions/changes on that document.

Points to note:
- Ideally the design will stay much the same as last year, so won't take too much time
- We'd like to really emphasise impact, hence the addition of the 'Show me the Impact' sections on every page

**Comment by MyfanwyNixon** [comment]
Suggested text for donation calls, if it's not to hard to add them in to each page at this stage: https://docs.google.com/document/d/1mg2NvleJrhMlGmD2_FQPdNkWS9ZHa31KhacAvIUkPkQ/edit#

**Comment by abimysoc** [comment]
Closing because it's now 2020...
