### ISSUE TITLE
Bug list

### ISSUE THREAD

**Issue by wrightmartin** [mysociety/annual-report#59]
## Transparency 

- [ ] "And, in a piece of inhouse research, we asked, who actually uses WhatDoTheyKnow?" I think this link is going to the wrong place - _just checked, and this is the link supplied in Google doc from @MyfanwyNixon_ 

## Community 
- [x] "Timing is everything. They also investigated when people make reports and what that tells us" I think this link is going to the wrong place

## TICTeC
- [x] The image for Neema Iyer from Pollicy's talk goes to the wrong talk
- [x] The image for Sruti Modekurty from OpenAQ's talk goes to the wrong talk

## Thanks
- [ ] Weird bug when you hover over the Esmee foundation link - it jumps up to a single line  (Safari) _on Safari v13.1.2 it's not doing it for me_

**Comment by wrightmartin** [comment]
"I started a YouTube channel." Can it link to it? :) https://www.youtube.com/channel/UCm1NZFx0iE5GzQJ6xDc0jIA?view_as=subscriber

**Comment by mySocietyClive** [comment]
All done
