### ISSUE TITLE
mySociety annual report 2021

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/annual-report#62]
Starting a ticket where we can discuss questions/requirements for the annual report 2021.

### Proposed deadlines:

**Copy finalised by**: 2 December
**Initial design completed by**: 9 December
**Comments, changes and snags completed by**:14 December
**Final proofreading**: 15 December
**Send date**: 16 December

@lucascumsille FYI, it feels like changes are always having to be made right up to deadline, including the addition of stats etc, but these are certainly the dates to aspire to. The final proofreading is often conducted by several staff members and they always find a few issues, so it's wise to keep that date relatively free if possible.

I've made a good start on the copy, so in fact I think it should be ready before 2 Dec; in any case I'm adhering to much the same template as our [2020 report](https://2020.mysociety.org/), so in theory it should be possible to lay out the basics even before the copy is finalised (one notable change is that we'll lead with the Climate section but that's presumably a minor design point).

Some important points to note for now:

- @sallytay is creating what we're calling (for now) a  [WDTK Transparency Report](https://github.com/mysociety/whatdotheyknow-theme/issues/910). This will be standalone and linked to from the Annual Report. No decision has yet been made about the design and hosting of this, but at its simplest it could be a mySociety blog post. More ambitiously, it could use elements of the annual report template for some sense of consistency? I'm happy to leave this decision to whichever designer takes the annual report on this year.
- @sallybracegirdle is creating the [SocietyWorks annual report](https://github.com/mysociety/societyworks/issues/2668), which we'll also link to from the Community section.

**Comment by MyfanwyNixon** [comment]
The first draft of the copy is now available on https://docs.google.com/document/d/1xexx4YBU5fofSZLAPAN5ddtjWyQP556LWyTZVQ7EbcI/edit#heading=h.9xqyqv28ku8k.

While it's far from finished, I think it's complete enough to make a start on the design. Shout if anything isn't clear!

**Comment by lucascumsille** [comment]
Thank you @MyfanwyNixon. I'll take a look and let you know 🙂
