### ISSUE TITLE
Need to find out the number of Git commits in 2014

### ISSUE THREAD

**Issue by zarino** [mysociety/annual-report#8]
It's empty!!!

![screen shot 2015-02-06 at 14 20 14](https://cloud.githubusercontent.com/assets/739624/6080665/46b3516a-ae0b-11e4-80d1-3c8921199f0b.png)

**Comment by dracos** [comment]
GitHub will give you commits to the master branch, in which case in the past year – note, not 2014 – it's 7182. That of course doesn't include branches, squashes, rebases, and everything like that, though. I can ignore the first bit of 2015, but then I can't include the first bit of 2014, so perhaps that'll do in some way?

**Comment by zarino** [comment]
7,182 seems sensible, given roughly the same amount of work probably got done in the first month of 2014 as in the first month of this year.
